### PR TITLE
Linux Compatibility

### PR DESCRIPTION
**Pull request by dabrowne**
Pyads now has Linux compatibility by wrapping the [open source ADS library](https://github.com/dabrowne/ADS) provided by Beckhoff. The main API is identical on both Linux and Windows, however the Linux implementation includes a built in router which needs to be managed programmatically using `pyads.add_route(ams_address, ip_address)` and `pyads.delete_route(ams_address)`.

Version 2.1.0 also features vastly improved test coverage of the API, and the addition of a dummy test server for full integration testing.

### CODE REVIEW

**Comment by MrLeeh** [comment]
Looks like a lot has happened in NZ :). I' m going to try your changes asap.

**Comment by dabrowne** [comment]
I've been busy ;)

I've tested pretty extensively on Linux and verified that my integration tests pass on Windows. Haven't touched much of the Windows code though so I wouldn't expect any issues there.

**Comment by MrLeeh** [comment]
How did you get the integration test running on Windows? Or did you do it manually?

**Comment by dabrowne** [comment]
`python -m unittest` from the root pyads directory should do it. If you get:
```
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
it's probably because you have the TwinCat service running on your local machine which will be already listening on the ADS port and stopping the test server from running (look for the `TCATSysSrv.exe` or `TwinCat System Service` in task manager and kill it).

**Comment by MrLeeh** [comment]
Now it's working. I had the TwinCat service running (like you said) so the testserver couldn't connect to the ADS port. Runs on Python2 and Python3. Great work.

**Pull request merged**
